[library.fusesoc-cores]
location = fusesoc_libraries/fusesoc-cores
sync-uri = https://github.com/fusesoc/fusesoc-cores
sync-type = git
auto-sync = true

[library.veerwolf]
location = fusesoc_libraries/veerwolf
sync-uri = https://github.com/chipsalliance/VeeRwolf
sync-type = git
auto-sync = true

