# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/liteDRAM.xdc

# XDC: imports/src/rvfpga.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_0 || ORIG_REF_NAME==BD_bidirec_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_1 || ORIG_REF_NAME==BD_bidirec_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_2 || ORIG_REF_NAME==BD_bidirec_0_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_3/BD_bidirec_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_3 || ORIG_REF_NAME==BD_bidirec_0_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_4/BD_bidirec_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_4 || ORIG_REF_NAME==BD_bidirec_0_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_5/BD_bidirec_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_5 || ORIG_REF_NAME==BD_bidirec_0_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_6/BD_bidirec_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_6 || ORIG_REF_NAME==BD_bidirec_0_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_7/BD_bidirec_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_7 || ORIG_REF_NAME==BD_bidirec_0_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_8/BD_bidirec_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_8 || ORIG_REF_NAME==BD_bidirec_0_8} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_9/BD_bidirec_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_9 || ORIG_REF_NAME==BD_bidirec_0_9} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_10/BD_bidirec_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_10 || ORIG_REF_NAME==BD_bidirec_0_10} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_11/BD_bidirec_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_11 || ORIG_REF_NAME==BD_bidirec_0_11} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_12/BD_bidirec_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_12 || ORIG_REF_NAME==BD_bidirec_0_12} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_13/BD_bidirec_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_13 || ORIG_REF_NAME==BD_bidirec_0_13} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_14/BD_bidirec_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_14 || ORIG_REF_NAME==BD_bidirec_0_14} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_15/BD_bidirec_0_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_15 || ORIG_REF_NAME==BD_bidirec_0_15} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_20/BD_bidirec_0_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_0_20 || ORIG_REF_NAME==BD_bidirec_0_20} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_0/BD_bidirec_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_1_0 || ORIG_REF_NAME==BD_bidirec_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_10_0/BD_bidirec_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_10_0 || ORIG_REF_NAME==BD_bidirec_10_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_11_0/BD_bidirec_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_11_0 || ORIG_REF_NAME==BD_bidirec_11_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_12_0/BD_bidirec_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_12_0 || ORIG_REF_NAME==BD_bidirec_12_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_13_0/BD_bidirec_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_13_0 || ORIG_REF_NAME==BD_bidirec_13_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_14_0/BD_bidirec_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_14_0 || ORIG_REF_NAME==BD_bidirec_14_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_15_0/BD_bidirec_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_15_0 || ORIG_REF_NAME==BD_bidirec_15_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_2_0 || ORIG_REF_NAME==BD_bidirec_2_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_0/BD_bidirec_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_3_0 || ORIG_REF_NAME==BD_bidirec_3_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_4_0/BD_bidirec_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_4_0 || ORIG_REF_NAME==BD_bidirec_4_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_5_0/BD_bidirec_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_5_0 || ORIG_REF_NAME==BD_bidirec_5_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_6_0/BD_bidirec_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_6_0 || ORIG_REF_NAME==BD_bidirec_6_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_0/BD_bidirec_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_7_0 || ORIG_REF_NAME==BD_bidirec_7_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_8_0/BD_bidirec_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_8_0 || ORIG_REF_NAME==BD_bidirec_8_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_9_0/BD_bidirec_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_bidirec_9_0 || ORIG_REF_NAME==BD_bidirec_9_0} -quiet] -quiet

# XDC: /home/fchacon/RVfpgaSoC/LabProjects/Lab1/Lab1.gen/sources_1/bd/BD/BD_ooc.xdc
